### ISSUE TITLE
XDG_CURRENT_DESKTOP hard set(?)

### ISSUE THREAD

**Issue by sewnie** [Kara-Zor-El/rust-fetch#1]
```
warning: unused imports: `BufReader`, `Error`
  --> src/main.rs:12:21
   |
12 | use std::io::{Read, Error, BufRead, BufReader};
   |                     ^^^^^           ^^^^^^^^^
   |
   = note: `#[warn(unused_imports)]` on by default

warning: unused import: `std::path::Path`
  --> src/main.rs:21:5
   |
21 | use std::path::Path;
   |     ^^^^^^^^^^^^^^^

warning: unused import: `BufRead`
  --> src/main.rs:12:28
   |
12 | use std::io::{Read, Error, BufRead, BufReader};
   |                            ^^^^^^^

warning: field is never read: `os`
  --> src/main.rs:27:5
   |
27 |     os: String,
   |     ^^^^^^^^^^
   |
   = note: `#[warn(dead_code)]` on by default

warning: `rust-fetch` (bin "rust-fetch") generated 4 warnings
    Finished dev [unoptimized + debuginfo] target(s) in 0.04s
     Running `target/debug/rust-fetch`
thread 'main' panicked at '$XDG_CURRENT_DESKTOP is not set: NotPresent', src/main.rs:43:10
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: core::result::Result<T,E>::expect
             at /builddir/rustc-1.57.0-src/library/core/src/result.rs:1258:23
   4: rust_fetch::main
             at ./src/main.rs:42:14
   5: core::ops::function::FnOnce::call_once
             at /builddir/rustc-1.57.0-src/library/core/src/ops/function.rs:227:5

```
currently, my window manager does not support setting `$XDG_CURRENT_DESKTOP`, but [this exists](https://github.com/Kara-Zor-El/rust-fetch/blob/54dd6d23a43a4b210423435aad021eb170dc3f85/src/main.rs#L43), i am no rust expert, so i'm not sure what is happening here. usually the way to check a window manager's name is using a tool such as [wmutils](https://github.com/wmutils) or how neofetch does it through checking all processes or something.

**Comment by Kara-Zor-El** [comment]
Hi, i am currently working on a fix for this. would you mind providing more details such as what WM your using and if its X11 or Wayland based?

**Comment by sewnie** [comment]
X11.
